### 获取token
POST {{host-sso}}:{{port}}/xxl-sso-server/app/login?username ={{username}}&password={{password}}
Accept:application/json
Cache-Control: no-cache

> {% client.global.set("token", response.body.data); %}

###


### 验证token
POST {{host-sso}}:{{port}}/xxl-sso-server/app/logincheck?sessionId={{token}}
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

###

### 退出token登录
POST {{host-sso}}:{{port}}/xxl-sso-server/app/logout?sessionId={{token}}
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

###

### 验证携带token 访问
GET {{host-sso}}:{{port}}/xxl-sso-token-sample-springboot/
Accept: application/json
Cache-Control: no-cache
xxl_sso_sessionid: {{token}}

###

